
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Rahul", email = "basicfunc@gmail.com"},
]
dependencies = [
    "torch>=2.0.1",
    "numpy>=1.24.3",
    "torchvision>=0.15.2",
    "opencv-python>=4.7.0.72",
]
requires-python = ">=3.10"
license = {text = "MIT"}
