
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Rahul", email = "basicfunc@gmail.com"},
]
dependencies = [
    "numpy>=1.24.3",
    "opencv-python>=4.7.0.72",
    "pytesseract>=0.3.10",
]
requires-python = ">=3.10"
license = {text = "MIT"}
